import pandas as pd
from utils.dataframe_treatment import treat_columns_names


class Cs1DataSetPreProcessing:
    """
    Process the DataFrame generated by the `credit_score_dataset_1.csv` file.

    I dropped the columns that the user can't answer easily or can't answer at all for ux purposes.

    Parameters:
        cs1_dataset (pd.DataFrame): The DataFrame to be processed.

    Returns:
        pd.DataFrame: The processed DataFrame.
    """

    @classmethod
    def process(cls, cs2_dataset: pd.DataFrame) -> pd.DataFrame:
        process_df = cs2_dataset.copy()
        process_df = treat_columns_names(process_df)

        return process_df
