// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
	BaseTranslation as BaseTranslationType,
	LocalizedString,
	RequiredParams
} from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'pt-BR';

export type Locales = 'en-US' | 'pt-BR';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
	/**
	 * S​c​o​r​e​ ​d​e​ ​C​r​é​d​i​t​o​ ​I​A
	 */
	credit_score_ai: string;
	validation: {
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​é​ ​o​b​r​i​g​a​t​ó​r​i​o​.
		 * @param {unknown} field
		 */
		required: RequiredParams<'field'>;
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​s​e​r​ ​p​o​s​i​t​i​v​o​.
		 * @param {unknown} field
		 */
		nonnegative: RequiredParams<'field'>;
	};
};

export type TranslationFunctions = {
	/**
	 * Score de Crédito IA
	 */
	credit_score_ai: () => LocalizedString;
	validation: {
		/**
		 * O campo '{field}' é obrigatório.
		 */
		required: (arg: { field: unknown }) => LocalizedString;
		/**
		 * O campo '{field}' deve ser positivo.
		 */
		nonnegative: (arg: { field: unknown }) => LocalizedString;
	};
};

export type Formatters = {};
